## IIBM Bootcamp 2025: Day 3 Morning

### Instructors Carlos Valle (cgvalle@uc.cl) and Nicolás Garrido (nagarrido@uc.cl)


This jupyter noteboook will cover the use of the NumPy and Matplotlib Python libraries and the Matlab equivalence.

### Day Agenda:

***Morning***
1. Working with NumPy
    * Arrays
    * Vector operations
    * Matrix operations
    * point-wise operations
2. Working with Matplotlib
    * Anatomy of a figure
    * Fundamental principles of ploting library
    * Design of a figure
    * Types of figures
    
3. Introduction to Matlab
    * Understanding the GUI
    * Vectors and Matrix
    * Plots

    
***Afternoon***

4. Group Project
    * Working with real-world data





# 1. Working with NumPy

NumPy is a Python library used for working with arrays (Matrix and Vectors) that contain numerical data (`float`, `int`). It is one of the most popular packages for scientific computing in Python. It provides multidimensional array definitions, optimizes execution code and several handy functions that are common while working with arrays.

Since NumPy is an external package to Python, it needs to be installed. Fortunately, Google Colab provides it by default. If it is not installed, you can installed running `pip install numpy` in your computer terminal. Let's see how to use it!.

First it needs to be imported with the line `import numpy`. However, it is common for this library to be loaded as `import numpy as np`, where now you can use it by only typing `np`.

In [1]:
import numpy as np  # NumPy is now imported and ready to be use

As mentioned before, NumPy is the defacto library for working with arrays. Let's create one:

In [7]:
# Out first numpy array
example_array = np.array([1, 2, 3, 4])

The variable `first_array` has a vector with the elements `[1, 2, 3, 4]`. If we check the type, it corresponds to a `numpy.ndarray`. `ndarray` is the type of the variable (like `int`, `float`, `list`, `dict`, etc.)

In [8]:
type(example_array)
print(example_array)

[1 2 3 4]


## Wait, is the input of `np.array` a list ?

# YES!

If we need a list to create and array, why don't we just use a list ?. The answer is that Python implementation of lists is not really fast. Let's test it by comparing the time of summing two arrays. We can use the magic function `%time` to obtain the execution time of the `python_sum` function.

In [9]:
vector_size = 100000

# Creating vectors
list_vector_A = list(range(vector_size))  # List
list_vector_B = list(range(10, vector_size + 10))  # List


In [10]:
def python_sum(vector_a, vector_b):
    final_vector = []
    N = len(vector_a)
    for i in range(N):
        final_vector.append(vector_a[i] + vector_b[i])

%time python_sum(list_vector_A, list_vector_B)

CPU times: user 16.7 ms, sys: 3.97 ms, total: 20.6 ms
Wall time: 21.4 ms


In [11]:
def numpy_sum(vector_a, vector_b):
    final_vector = vector_a + vector_b

%time numpy_sum(list_vector_A, list_vector_B)

CPU times: user 2.17 ms, sys: 19 µs, total: 2.19 ms
Wall time: 2.2 ms


Not only the NumPy way was **faster**, but also a **much simpler**.

## Arrays: `ndarray` objects have a lot of useful information and methods

Some usefull methods are:
### [`ndarray.shape` ](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.shape.html) returns dimension of the array

In [12]:
# A list only has one dimension!
array = np.array([1, 2, 3, 4])
array.shape

(4,)

In [14]:
a=[[1, 2, 3, 4]]
print(len(a))

1


In [13]:
# A list inside a list has two dimension!
array = np.array([[1, 2, 3, 4]])
array.shape

(1, 4)

In [15]:
# A list inside a list inside a list has three dimensions!
array = np.array([[[1, 2, 3, 4]]])
array.shape

(1, 1, 4)

### [`ndarray.dtype` ](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.dtype.html) returns the type of number inside

In [16]:
# Since all numbers inside are int, the type is also a int
array = np.array([[1, 2, 3, 4]])
array.dtype

dtype('int64')

In [17]:
# Since all numbers inside are float, the type is also a float
array = np.array([[1.0, 2.0, 3.0, 4.0]])
array.dtype

dtype('float64')

In [18]:
# Since one of the numbers inside is a float, the type is also a float
array = np.array([[1.0, 2, 3, 4]])
array.dtype

dtype('float64')

### [`ndarray.T` ](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.T.html)  return a transpose array

In [19]:
array = np.array([[1.0, 2, 3, 4]])
print("Original Array dimension:", array.shape)

array_transpose = array.T
print("Original Array dimension:", array_transpose.shape)

Original Array dimension: (1, 4)
Original Array dimension: (4, 1)


## Arrays can have lots of dimension

In [22]:
multi_dim_array = np.random.rand(4, 3, 2, 5)
print(multi_dim_array)
#print(multi_dim_array.shape)

[[[[7.17168497e-01 7.89033295e-02 2.32293274e-01 2.79318525e-01
    1.40759718e-01]
   [5.03849898e-01 4.08025321e-01 8.85321752e-01 6.22754107e-01
    6.03258503e-01]]

  [[7.94579787e-02 1.77114880e-01 8.16370755e-01 9.94143774e-01
    3.71295654e-01]
   [9.43193233e-01 7.26504264e-01 6.42777474e-01 2.96819836e-01
    3.36510185e-01]]

  [[5.60646941e-01 4.53714968e-01 9.25834897e-01 9.72582229e-01
    1.40895066e-01]
   [7.37936148e-01 1.18855063e-01 5.97947990e-01 7.03426782e-01
    8.15616564e-01]]]


 [[[9.91773402e-02 1.20348403e-01 7.23249725e-01 9.21999295e-01
    4.88452351e-02]
   [1.36345973e-02 3.80696639e-01 7.63625825e-01 1.48933887e-01
    6.29895512e-01]]

  [[1.93032719e-01 2.41022335e-01 4.90595366e-01 7.80241347e-01
    1.96639944e-01]
   [6.94984361e-01 5.54078986e-01 5.95831998e-01 1.66357189e-01
    2.37659238e-01]]

  [[5.20610419e-01 9.88475440e-01 5.42476535e-01 9.08148118e-01
    4.35209977e-01]
   [7.99178346e-01 9.90363060e-01 3.12263933e-01 4.41795061e-01


## [Array Multiplication](http://matrixmultiplication.xyz/)

![multiplication](https://raw.githubusercontent.com/cgvalle/IIBM-BootCamp-2024/main/assets/D3/matrix_mul.png)

## Vector normal multiplication

In [24]:
# Normal multiplication
array_1 = np.array([[1, 2, 3, 4]])
array_2 = np.array([[1, 2, 3, 4]]).T
#print(array_1.shape)
#print(array_2.shape)
np.matmul(array_1, array_2)

array([[30]])

## Vector dot multiplication

In [25]:
array_1 = np.array([[1, 2, 3, 4]])
array_2 = np.array([[1, 2, 3, 4]])
array_1 * array_2 # Dot product

array([[ 1,  4,  9, 16]])

## Matrix normal multiplication

In [27]:
matrix_1 = np.array([[1, 0], [0, 1]])
matrix_2 = np.array([[4, 1], [2, 2]])
print(matrix_1.shape)
print(matrix_2.shape)
np.matmul(matrix_1, matrix_2)

(2, 2)
(2, 2)


array([[4, 1],
       [2, 2]])

## Matrix dot multiplication

In [28]:
matrix_1 = np.array([[1, 0], [0, 1]])
matrix_2 = np.array([[4, 1], [2, 2]])
matrix_1 * matrix_2

array([[4, 0],
       [0, 2]])

Mores methods `ndarray` can be found [here](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)

## 1.1 Exercise

Create a numpy array with the shape and values:
$$
array =
\left [ \begin{array}{c}
0.8 & 1.2\\
-0.4 & -0.1\\
-0.6 & -0.9
\end{array}\right ]
$$

In [33]:
array = np.array([[0.8, 1.2], [-0.4, -0.1], [-0.6, -0.9]])
print(array)

[[ 0.8  1.2]
 [-0.4 -0.1]
 [-0.6 -0.9]]


## 1.2 Exercise

Sum all the elements of the previous array

In [34]:
array_sum = np.sum(array)

## 1.3 Exercise

Multiply the array by itself. **HINT: you may need to transpose!**

In [35]:
array_multi = np.matmul(array, array.T)

## 1.4 Exercise

Point-wise multiplication of created array.

In [36]:
array_point = array * array

# 2. Working with Matplotlib



# Anatomy of a figure


![](https://raw.githubusercontent.com/cgvalle/IIBM-BootCamp-2024/main/assets/D3/anatomy_of_figure.png)
***Scientific Visualization: Python + Matplotlib, 2021 Nicolas P.Rougier.***
Book available for free at [rougier/scientific-visualization-book](https://github.com/rougier/scientific-visualization-book)

Scientific visualization is a graphical interface
between people and data... so be clear!

Some tips to improve figure design:
* Identify your menssage: 'A picture is worth a thousand words'
* Know Your Audience: Know the familiarity with the plots according to field, journal, etc
* Use Color Effectively
* Do Not Trust the Defaults

## Basic usage

In [ ]:
# Import libraries
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# Most simplest plot
# Identify the default values
plt.plot(range(10))
plt.show()

In [ ]:
# Is this plot different ?
plt.plot(range(100))
plt.show()

## DESIGN OF A FIGURE - Customize your plot


```plt.plot``` automatically create the OBJECT 'figure' and 'axes' to achieve the basic plot.

Some good practices is to


1.   Customize your plot: Define the figure and axes
2.   Use the methods: Method will start adding plot elements (lines, images, text, etc.) to the object figure.


So first we will create a figure ```figure_name= plt.figure(figsize=(a,b)) ``` , and the axes ```ax_name=plt.subplot(nrows,ncol,index) ```

In [ ]:
fig1 = plt.figure(figsize=(8, 4))

In [ ]:
ax1 = plt.subplot(1, 1, 1)

We can define an array with ``` np.linspace(start,stop,num) ```. Return evenly spaced numbers [np.linspace](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

In [ ]:
# array
x = np.linspace(0, 10, 100)
print(x)

And plot it with the default values

In [ ]:
fig1= plt.figure()
ax1=plt.subplot(1, 1, 1)
linea= ax1.plot(x)
plt.show()

In order to control the AXES limits of the figure; we add ```ax.set_xlim() ``` and  ```ax.set_ylim() ```

In [ ]:
fig1= plt.figure()
ax1=plt.subplot(1, 1, 1)
linea= ax1.plot(x)
ax1.set_xlim(0, 100)
ax1.set_ylim(0, 1)
plt.show()

In [ ]:
# With the same numpy array information we can create a sin wave
fig2= plt.figure(figsize=(8, 4))
ax2=plt.subplot(1, 1, 1)
line=ax2.plot(x, np.sin(x))
ax2.set_xlim(0, 10)
ax2.set_ylim(-1, 1)
plt.show()

```np.sin()``` calculate the trigonometric sine of the variable for all the elements.

For a better explanation, we add titles, legends, and labels

In [ ]:
fig2= plt.figure(figsize=(8, 4))
ax2=plt.subplot(1, 1, 1)
line=ax2.plot(x, np.sin(x))
plt.title('Sine Plot')
plt.xlabel('x-axis')
plt.ylabel('y-axis')
ax2.set_xlim(0, 10)
ax2.set_ylim(-1, 1)
plt.show()

In [ ]:
# We can plot both figures in one plot

plt.figure(figsize=(8, 4)) #generate the figure
ax1=plt.subplot(1, 2, 1) #first subplot
line=ax1.plot(x, np.sin(x))
ax2=plt.subplot(1, 2, 2) #second subplot
line=ax2.plot(x, np.sin(x))
plt.suptitle('Both sines plots') # a title
plt.show()

## Colors

*Use Color Effectively*


In [ ]:
## ADD COLORS to the plots
fig3= plt.figure(figsize=(8,4))
ax3=plt.subplot(1,1,1)
line=ax3.plot(x, np.sin(x), color='green', marker='o') #here we add green markers to the line
plt.title('Sine Plot with blue dots')
plt.xlabel('x-axis')
plt.ylabel('y-axis')
ax3.set_xlim(0,10)
ax3.set_ylim(-1,1)
plt.show()

In [ ]:
## ADD COLORS to the plots
fig3= plt.figure(figsize=(8,4))
ax3=plt.subplot(1,1,1)
line=ax3.plot(x, np.sin(x), color='green', marker='o') #here we add green markers to the line
line=ax3.plot(x, np.cos(x), color='pink', marker='*')
plt.title('Sine Plot with blue dots')
plt.xlabel('x-axis')
plt.ylabel('y-axis')
ax3.set_xlim(0,10)
ax3.set_ylim(-1,1)
plt.show()

In [ ]:
inicio = np.array([1,2,3,4,5])
final = np.array([5,6,7,8,9])

plt.plot(inicio, inicio, color='red')
plt.plot(final, final, color='darkblue')

plt.show()

We also can plot a image of the data by using ```imshow```
Check [imshow](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.imshow.html)

In [ ]:
# PLOT a the result of a MARTRIX multiplication
matrix_1 = np.array([[1, 0], [0, 1], [5, 6]]) # (3,2)
matrix_2 = np.array([[4, 1], [2, 2]]) # (2,2)
data = np.matmul(matrix_1, matrix_2)

plt.imshow(data, cmap='hot') #plot the data
plt.colorbar() # add the colorbar

## Excersise 2.1 Plot multiple cos and sin functions

![](https://raw.githubusercontent.com/cgvalle/IIBM-BootCamp-2024/main/assets/D3/a_nice_plot.png)

From the code below create a similar plot as the one shown above.

In [ ]:
# Initialize the figure
'<TO DO>'=plt.figure(figsize=('<TO DO>'))
ax=plt.subplot('<TO DO>')


# Generate content
circle= np.linspace('<TO DO>', 2*np.pi, '<TO DO>')
line=ax.plot(circle, np.sin(circle), color='TO DO')
ax.set_xlim('<TO DO>')
ax.set_ylim('<TO DO>')


# Add title and labels
plt.title('<TO DO>')
plt.xlabel('<TO DO>')
plt.ylabel('<TO DO>')
plt.legend('<TO DO>')

# Display plot
'<TO DO>'

# 3. Introduction to Matlab

![](https://raw.githubusercontent.com/cgvalle/IIBM-BootCamp-2024/main/assets/D3/matlab_logo.png)

Matlab (**MAT**trix **LAB**oratory) is a proprietary programing language. Unlike Python, a suscription is associated to the base program and its toolboxes (or libraries). Luckely, the university provides licenses to studes free of charge. If you already have an uc email, follow the steps described [informatica UC](https://informatica.uc.cl/licencias#mathworks-matlab-campus-agreement). If not, a one moth free trial of matlab can be downloaded directly from the official [MathWorks page](https://la.mathworks.com/campaigns/products/trials.html).



![](https://raw.githubusercontent.com/cgvalle/IIBM-BootCamp-2024/main/assets/D3/matlab_environment.png)




Matlab provides a GUI by default. It is composed of:

    * Current folder: Aside from default funcitons, Matlab can only find code in the current folder. Make you that the scripts, images, data, etc. are in the current folder, otherwise you will need additional steps for Matlab to find them.
    
    * File editor Window: Here you can write code!
    
    * Workspace: This window shows all defined variables. Matlab will store variable values even if the variable is deleted from the script. You need be aware of persistant variables and what effect they can have on the code.
    
    * Command Window: You can run commands or functions here to add functions or variables that you don't want in your script. Useful functions like `whos`, `clc` or `clear` are usually use here.

## How similar it is to python ?  A lot


![](https://raw.githubusercontent.com/cgvalle/IIBM-BootCamp-2024/main/assets/D3/matlab_python.png)
Source: https://realpython.com/matlab-vs-python



## Comments

<table style='font-family:"Courier New", Courier, monospace; font-size:150%;width:100%'>
<tr>
<th style="text-align:left" > Matlab </th>
<th style="text-align:left" > Python </th>
</tr>
<tr>
<td style="text-align:left;vertical-align:top;padding:0" >

       
```c++
array = [1, 2, 3, 4]
% new_array = array + 2
```

</td>
<td style="text-align:left;vertical-align:top;padding:0">

```python
array = [1, 2, 3, 4]
# new_array = array + 2
```

</td>
</tr>
</table>

`%` simbol is used for comments Matlab and `#` simbol for Python.

<hr style="border:1px solid gray">


## Arrays

<table style='font-family:"Courier New", Courier, monospace; font-size:120%;width:100%'>
<tr>
<th style="text-align:left" > Matlab </th>
<th style="text-align:left" > Python </th>
</tr>
<tr>
<td style="text-align:left;vertical-align:top;padding:0" >

       
```c++
vector = [1 2 3 4] % "," is not mandatory
```

</td>
<td style="text-align:left;vertical-align:top;padding:0">

```python
array = [1, 2, 3, 4] # "," is mandatory
```

</td>
</tr>
</table>

<hr style="border:1px solid gray">


## Matrixs

<table style='font-family:"Courier New", Courier, monospace; font-size:100%;width:100%'>
<tr>
<th style="text-align:left" > Matlab </th>
<th style="text-align:left" > Python </th>
</tr>
<tr>
<td style="text-align:left;vertical-align:top;padding:0" >

       
```c++
matrix = [1 2 3; 4 5 6; 7 8 9] % 3x3 matrix
```

</td>
<td style="text-align:left;vertical-align:top;padding:0">

```python
import numpy as np
# 3x3 matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```

</td>
</tr>
</table>
Matlab is designed for mathematical computations, while python needs additional steps as list don't have the properties of matrix by default and `Numpy` library needs to be use.
<hr style="border:1px solid gray">


## Starting index

<table style='font-family:"Courier New", Courier, monospace; font-size:100%;width:100%'>
<tr>
<th style="text-align:left" > Matlab </th>
<th style="text-align:left" > Python </th>
</tr>
<tr>
<td style="text-align:left;vertical-align:top;padding:0" >

       
```c++
% First index is 1
array = [23 75 32 7]
array(2) % is 75
    
```

</td>
<td style="text-align:left;vertical-align:top;padding:0">

```python
# First index is 0
array = [ 23, 75, 32, 7]
array[2] # is 32
```

</td>
</tr>
</table>

Arrays starts at 1 in Matlab while in Python at 0
<hr style="border:1px solid gray">



## Slicing

<table style='font-family:"Courier New", Courier, monospace; font-size:100%;width:100%'>
<tr>
<th style="text-align:left" > Matlab </th>
<th style="text-align:left" > Python </th>
</tr>
<tr>
<td style="text-align:left;vertical-align:top;padding:0" >

       
```c++
% First index is 1
array = [23 75 32 7]
array(2) % () round parentesis
    
```

</td>
<td style="text-align:left;vertical-align:top;padding:0">

```python
# First index is 0
array = [ 23, 75, 32, 7]
array[4] # brackets
```

</td>
</tr>
</table>

To call a value in a array matlab uses `()` while python `[]`. The funcionality is the same but the syntaxis is different.
<hr style="border:1px solid gray">


## Functions

<table style='font-family:"Courier New", Courier, monospace; font-size:100%;width:100%'>
<tr>
<th style="text-align:left" > Matlab </th>
<th style="text-align:left" > Python </th>
</tr>
<tr>
<td style="text-align:left;vertical-align:top;padding:0" >

       
```c++
sumar(1,2)
    
function total = sumar(x, y)
    total = x + y
end
```

</td>
<td style="text-align:left;vertical-align:top;padding:0">

```python
def sumar(x, y):
    return x + y
    
sumar(1,2)
```

</td>
</tr>
</table>

<hr style="border:1px solid gray">

Matlab functions must be define at the bottom of the script (`.m` extension) and require a `end` to indicate the end of the function. Unlike Python, indentation is not a concern on Matlab.

We just cover the essential syntaxis differences between both languages. There are more differences that you will find while experimenting with the code!.

**<p style="text-align: center;font-size:220%">Syntaxis is different but logic is the same!**

# Array and Matrix multiplication on Matlab



### Vector normal Multiplication
```R
arr_1 = [1 2 3]     % shape (1, 3)
arr_2 = [4, 5 6]    % shape (1, 3)
arr_1 * arr_2       % -> (1,3) x (1,3) multiplication is not possible
arr_1 * arr_2.'       % -> (1,3) x (3,1) = 32
```
`.'` is use to transpose arr_2.


### Vector dot (pointwise) multiplication
```R
arr_1 = [1 2 3]     % shape (1, 3)
arr_2 = [4, 5 6]    % shape (1, 3)
arr_1 .* arr_2      % -> [4 10 18]
```


## Matrix normal multiplication
```R
mat_1 = [1 2 3; 4 5 6; 6 7 8]
mat_2 = [3 4; 2 4; 6 8]
mat_1 * mat_2       % (3,3) x (3,2) -> (3,2) = [25 36; 58 84; 80 116]
```


## Matrix dot (pointwise) multiplication
```R
mat_1 = [1 2; 4 5]
mat_2 = [3 4; 2 4]
mat_1 .* mat_2       % (2,2) x (2,2) -> (2,2) = [7 12 ; 22 36]
```


# Ploting

Matlab doesn't require a external ploting library. Similar to Python, let's start by defining the `x` and `y = f(x)` values

```R
x = [0:100]  # array with numbers from 0 to 100
y = cos(x/10)
```

To create a plot, just call the `plot` function.
```R
plot(x, y)
```

![](https://raw.githubusercontent.com/cgvalle/IIBM-BootCamp-2024/main/assets/D3/matlab_plot.png)

Let's customize the figure
```R
plot(x,y)
xlabel('X axes')
ylabel('Y label')
title('A nice title')
xlim([0, 50])
```

![](https://raw.githubusercontent.com/cgvalle/IIBM-BootCamp-2024/main/assets/D3/matlab_plot_custom.png)

### Multiple functions on the same figure



```R
x = 1:100
y1 = cos(x/10)
y2 = sin(x/10)

plot(x, y1, x, y2)
xlabel('X axes')
ylabel('Y label')
title('A nice title')
xlim([0, 50])
```


![](https://raw.githubusercontent.com/cgvalle/IIBM-BootCamp-2024/main/assets/D3/matlab_plot_multiple.png)


# Don't forget to send your work!

Please don't forget to send your work to give you feedback about your progress to this [form](https://forms.gle/sME7JXuoB4ztMCFq6). To send it, you need to download the Notebook from Colab's webpage and upload it in the last question of the form.
